# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sitio-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sitio
  template:
    metadata:
      labels:
        app: sitio
    spec:
      containers:
      - name: sitio-container
        image: sitio_k8s:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sitio-service
spec:
  type: NodePort
  selector:
    app: sitio
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30555
